# Generated by Django 3.2.25 on 2024-07-09 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='model_year',
            field=models.PositiveIntegerField(default=2000),
        ),
    ]
